name: Terraform CI/CD

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Init Terraform
      run: terraform -chdir=terraform init

    - name: Validate Terraform
      run: terraform -chdir=terraform validate
